apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  labels:
    app: my-approuter
  name: my-approuter
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: my-approuter
  rules:
    - path: /.*
      methods: ["GET", "POST", "PUT", "DELETE"]
      service:
        name: my-approuter
        port: 5000
      accessStrategies:
        - handler: noop
      mutators:
        - handler: header
          config:
            headers:
              x-forwarded-host: "my-approuter.c-24084ae.kyma.ondemand.com"
