apiVersion: v1
kind: ConfigMap
metadata:
  name: destinations
data:
  destinations: >-
    [
        {
          "name": "frontend",
          "url": "https://app7.c-24084ae.kyma.ondemand.com",
          "forwardAuthToken": true
        }
    ]
---
apiVersion: v1
data:
  xs-app.json: |-
    {
        "authenticationMethod": "route",
        "sessionTimeout": 10,
        "routes": [
         {
            "source": "^/(.*)$",
            "destination": "frontend",
            "target": "https://app7.c-24084ae.kyma.ondemand.com/$1",
            "authenticationType": "xsuaa"
         }
        
        ]
    }
kind: ConfigMap
metadata:
  name: xs-app
